# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
before:
  hooks:
  - nix flake check -L -v
binary_signs:
- ids:
  - schema2nix
builds:
- id: schema2nix
  main: ./cmd/schema2nix
  binary: bin/schema2nix
  flags:
  - -trimpath
  ldflags:
  - -s
  - -w
  - -buildid=
  - -X main.version={{.Version}}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: amd64
  - goos: windows
    goarch: arm64
changelog:
  disable: true
checksum:
  name_template: checksums.txt
gomod:
  proxy: true
  mod: readonly
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
nfpms:
- id: schema2nix
  ids:
  - schema2nix
  formats:
  - apk
  - archlinux
  - deb
  - rpm
  vendor: William Artero
  homepage: https://github.com/wwmoraes/schema2nix
  maintainer: William Artero <contact@artero.dev>
  description: converts JSON schemas to nix options
project_name: schema2nix
release:
  github:
    owner: wwmoraes
    name: schema2nix
  prerelease: auto
signs:
- artifacts: all
  ids:
  - schema2nix
snapshot:
  version_template: "{{- .RawVersion -}}+{{ .FullCommit }}"
